client_credentials:
  token: eBlXRdLQNW6nbPb6grYp05BXsq0UHIz47nFik7sS
  address: https://testnet-algorand.api.purestake.io/ps2

main_developer_credentials:
  private_key: ePGmYLZdz+xy4WtpC2t6SQVpfziz2gBU5Cm9TuPBLyi04PvbcTycLdRFkodnU1fyJP5v9HrRV2zQTBGW86mV/g==
  #i6A1HWNWKTzGUMKHnYuRegIFy+YTE/NnlUNePp4pJ8b4XGjLTkFOHs1nhr6RSywczUD+Ga3TTT4/CFOefKNn6g==
  #0jYcsquKG4hl/G+CMy5FojXdalTnO4BaNAnoW79ytAaIQPie50zq1KoymOOyEYDE0vbyHGhkvd/EblLddHvsiw==
  #v4urx8IHyn7mewgmvU30o8oCP6hZ1uS8qlkbBJ4zL0ijBEAZTogKuSkANn16caBET/v0rlBIOxVFuMpa3XLRCg==
  #8pKZyOZzxvtCVI4QQXyaqrxvly3GTyZLWWtmXTYuFMbNL9EDLDvzSxTVkcIXOVJCkpJAJYGBkfGPvatXmEhb/g==
    #WlHHGYCDrrU+Fdfm3DWmeZdV5liUT+HpDH/ra8vufeQ8qZFx1IEdB//wsr7ONnqphwtDu3+/slap/4np0MhXJA==
  public_key: WTQPXW3RHSOC3VCFSKDWOU2X6ISP437UPLIVO3GQJQIZN45JSX7I4FWNDU
  #7BOGRS2OIFHB5TLHQ27JCSZMDTGUB7QZVXJU2PR7BBJZ47FDM7VBU4QGBQ
  #RBAPRHXHJTVNJKRSTDR3EEMAYTJPN4Q4NBSL3X6ENZJN25D35SFTE3PNZQ
  #UMCEAGKORAFLSKIAGZ6XU4NAIRH7X5FOKBEDWFKFXDFFVXLS2EFA74XLZM
  #ZUX5CAZMHPZUWFGVSHBBOOKSIKJJEQBFQGAZD4MPXWVVPGCILP7PBPSJTA
  #HSUZC4OUQEOQP77QWK7M4NT2VGDQWQ53P673EVVJ76E6TUGIK4SM7KQZ7Y

developer_1_credentials:
  private_key: Rbo/+rvBu3s+y9GcvdrYhMTFTeeJJak5tk88vuczwJ2ntUNlZr8wQZzNEodvtZA4Y+hD88I695oeocwmnRXxTw==
  #4EGl5uwnU0Rjv2XAB05n0s+ahf9OoUgD9xT03G3K+L/3nscbcpEB4HhOh/ldzAFrqXqrcOGj2urStkiLvNDt2Q==
  public_key: U62UGZLGX4YEDHGNCKDW7NMQHBR6QQ7TYI5PPGQ6UHGCNHIV6FHQWDBDVM
  #66PMOG3SSEA6A6COQ74V3TABNOUXVK3Q4GR5V2WSWZEIXPGQ5XM3PLB4WA
